name: Simple workflow

on: workflow_dispatch

jobs: 
  my_first_job:
    name: first job
    runs-on: [self-hosted]
    steps: 
      - name: print hello world
        run: echo "hello world actionj"
