name: Terraform CI

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  production-deploy:
    runs-on: runnerbhai   # Aapka self-hosted runner ka naam

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v5

      # Step 4: Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5   # Stable version (use your preferred version)

      # Step 5: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 6: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 7: Terraform Plan
        # Plan output file optional (for later apply)
      - name: Terraform Plan
        run: terraform plan -out=tfplan


      

      
